meal-sharing
Hailegebriel22/meal-sharing pull request #2
Opened 2022-09-15 12:30 UTC by Hailegebriel22

2022-09-18 09:01 UTC, itsgauravsaxena requested changes

2022-09-18 09:01 UTC, itsgauravsaxena commented on src/backend/api/reservations.js
> +    const reservations = await knex("Reservation").select("*");
You could also use select() and not put *

2022-09-18 09:01 UTC, itsgauravsaxena commented on src/backend/app.js
> +
unnecessary line breaks

2022-09-18 09:01 UTC, itsgauravsaxena commented on src/backend/app.js
> +    res.status(404).json({ message: 'No meals' })
This error code makes no sense when creating/inserting new meal

2022-09-18 09:01 UTC, itsgauravsaxena commented on src/backend/app.js
> +  }
try catch is missing - its always a good idea to add that especially doing DML operation against database or external services

2022-09-18 09:01 UTC, itsgauravsaxena commented on src/backend/app.js
> +  const updatedmeal = await knex('meals').where({ "id": request.params.id }).update({
When doing PUT/Update, its always good idea to do do a lookup/select and see if record that you are trying to update exists.

2022-09-18 09:01 UTC, itsgauravsaxena commented on src/backend/app.js
> +
too many line breaks

2022-09-18 09:01 UTC, itsgauravsaxena commented on src/backend/app.js
> +router.get('/', async (req, res) => {
app.js shouldn't have this implementation of apis/routes but instead they should be  moved to meals.js and reservation.js

2022-09-19 22:25 UTC, Hanouj reviewed
Nice work Haile you a really god job on this homework

2022-09-19 22:25 UTC, Hanouj commented on src/backend/api/meals.js
> +    title: request.body.title,
Nice work Haile 
it would've been better to store request.body in a variable 
like:  addMeal = request.body;
then you dont need to write the whole thing

2022-09-19 22:25 UTC, Hanouj commented on src/backend/api/meals.js
> +    response.status(201).json({ id: request.params.id, message: "meal deleted" })
really nice with the msg

2022-09-19 22:25 UTC, Hanouj commented on src/backend/api/meals.js
> +    title: request.body.title || "Untitled",
Id also suggest to store request.body in a variable

2022-09-20 20:51 UTC, merged